# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-12.04.2"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
  config.vm.provider :virtualbox do |vb|    
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
  end
  config.vm.network "private_network", ip: "192.168.50.4"
  #config.vm.provision :puppet do |puppet|
  #  puppet.module_path = "puppet/modules"
  #  puppet.manifests_path = "puppet"
  #  puppet.manifest_file  = "init.pp"    
  #end
end
